### ISSUE TITLE
Repository hand off

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/reflect#31]
@8BitMate some things you'll want to do:

- Go to https://crates.io/me/pending-invites, accept the owner invite for both `reflect` and `reflect-internal`.

- Go to https://github.com/8BitMate/reflect/settings, check the right box under Features to enable Issues so your repo gets its own issue tracker.

- Go to https://github.com/8BitMate/reflect/subscription, select to watch the repo so you get notified about new issues and pull requests.

**Comment by Tomaz-Vieira** [comment]
Is `8BitMate/reflect` still the official home of the `reflect` project? I see some commits in `dtolnay/reflect` from 2 months ago but `8BitMate/reflect` had its last commit one year ago.

Also, Github tells me that `8BitMate/reflect` is "98 commits ahead, 21 commits behind dtolnay:master.", so there is stuff in both repos missing from the other one.

I wanted to try it out, which one should I use?

**Comment by 8BitMate** [comment]
So, I was working on this project for my master thesis, and I had intentions on continuing working on it afterwards, but after getting a job I found that programming every workday is enough for me. I also kinda forgot about this project.

From my perspective, I'm cool with making this the official repo again, and viewing my fork as more of an experiment. I'm also open to merging my changes back into this repo, but that might require some touch ups on my end. Thinking about it now, if someone else wants to continue with this project, it might be easier to start developing from this repo, since I don't remember exactly how I designed what I did, and what the limitations are. The main difference between this repo and my fork, is that I added some basic functionality for generics, but it isn't complete or very well tested.

Also, if this becomes this becomes the official repo again, I don't mind if you (or anyone else) takes inspiration or uses code from my fork.
